version: '3.8'
services:
  db:
    image: postgres:16.2-alpine
    command: -p 5432
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - app-db-data:/var/lib/postgresql/
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  app:
    build: 
      context: .
    env_file:
      - .env
    command: "bash docker.sh"
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  app-db-data: